# Prepare a temporary/builder container for building the app
FROM arm32v7/erlang:23-slim as builder

# Install required packages
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    git wget curl tar bzip2 autoconf automake pkg-config \
    libdbus-1-dev cmake

# Add source code
WORKDIR /usr/src/gateway-config
ADD . /usr/src/gateway-config/

# Build source code as a tar file
ENV CC=gcc CXX=g++ ERL_COMPILER_OPTIONS="[deterministic]"
RUN ./rebar3 as prod tar

# Extract tar (to copy files into the final container image)
RUN mkdir -p /opt/gateway-config
RUN tar -zxvf /usr/src/gateway-config/_build/prod/rel/*/*.tar.gz -C /opt/gateway-config

# Prepare final container image
FROM arm32v7/erlang:23-slim

# Install required packages
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    libdbus-1-3
#RUN apt-get install -y dbus bluez conman

# Prepare installation directory
WORKDIR /opt/gateway-config
ENV PATH=$PATH:/opt/gateway-config/bin

# Copy files from built by the builder container
COPY --from=builder /opt/gateway-config/ /opt/gateway-config/
RUN cp /opt/gateway-config/config/com.helium.Config.conf /etc/dbus-1/system.d/com.helium.Config.conf

# Define default process to execute for the container
CMD ["/opt/gateway-config/bin/gateway_config"]